@startuml
'メニュー画面'
[*] --> メニュー画面
メニュー画面 --> ルール画面 : ルールを押す
メニュー画面 --> ランキング画面 : ランキングを押す
メニュー画面 --> 遊び方画面 : 遊び方を押す
メニュー画面 --> 各種設定画面 : 各種設定を押す


'ルール画面'
ルール画面 --> マインスイーパー画面 : スタートを押す
ルール画面 --> メニュー画面 : 戻るを押す

'マインスイーパー画面'
マインスイーパー画面 --> メニュー画面 : ホームを押す
マインスイーパー画面 --> ルール画面 : ルール変更を押す
マインスイーパー画面 --> マインスイーパー画面 : リトライを押す

'ランキング画面'
ランキング画面 --> メニュー画面 : 戻るを押す

'各種設定画面'
各種設定画面 --> メニュー画面 : 戻るを押る

@enduml
